name: Bruno Dayan Photography
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: America/New_York

s3url: https://s3.amazonaws.com/brunodayanphotography

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
