name: Bruno Dayan Photography
markdown: kramdown
highlighter: pygments
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: America/New_York

s3url: https://s3.amazonaws.com/brunodayanphotography

gems:
  - jekyll-sitemap
